import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useUser } from '@auth0/nextjs-auth0';
import Hero from '../components/home/hero';
import SubHero from '../components/home/subHero';

export default function Home() {
  const { user, error, isLoading } = useUser();
  /*console.log(user)*/

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  if (user) {
    return (
      <div>
        Welcome {user.name}! <a href="/api/auth/logout">Logout</a>
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>LB FITNESS │ Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <a href="/api/auth/login">Login</a>

      <Hero/>
      <SubHero/>
       
    </div>
  )
}

{/* <div className={styles.container}> */}